apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: zerosecret
      type: Opaque
      data:
        - objectName: ASPNETCORE_ENVIRONMENT
          key: ASPNETCORE_ENVIRONMENT
        - objectName: ZC_DB__DATABASENAME
          key: ZC_DB__DATABASENAME
        - objectName: ZC_DB__PASSWORD
          key: ZC_DB__PASSWORD
        - objectName: ZC_DB__SERVERURL
          key: ZC_DB__SERVERURL
        - objectName: ZC_DB__USERNAME
          key: ZC_DB__USERNAME
        - objectName: PAT
          key: PAT
        - objectName: USER_VARIABLE
          key: USER_VARIABLE
        - objectName: ZC_DB__AUTHENTICATIONTYPE
          key: ZC_DB__AUTHENTICATIONTYPE
  parameters:
    objects: |
      - objectName: ZeroSecret
        objectType: secretsmanager
        jmesPath:
          - Path: ASPNETCORE_ENVIRONMENT
            ObjectAlias: ASPNETCORE_ENVIRONMENT
          - Path: ZC_DB__DATABASENAME
            ObjectAlias: ZC_DB__DATABASENAME
          - Path: ZC_DB__PASSWORD
            ObjectAlias: ZC_DB__PASSWORD
          - Path: ZC_DB__SERVERURL
            ObjectAlias: ZC_DB__SERVERURL
          - Path: ZC_DB__USERNAME
            ObjectAlias: ZC_DB__USERNAME
          - Path: PAT
            ObjectAlias: PAT
          - Path: USER_VARIABLE
            ObjectAlias: USER_VARIABLE
          - Path: ZC_DB__AUTHENTICATIONTYPE
            ObjectAlias: ZC_DB__AUTHENTICATIONTYPE