apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "zeroconnectapi.fullname" . }}
  labels:
    {{- include "zeroconnectapi.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsName }}"
        objectType: "secretsmanager"
